---
title: "Data stuffies"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
load("tanh_Ba-5100_data.RData")
library(ggplot2)
```

## R Markdown
```{r summary Ba_hat}
## Results: avg. parameter, bias, variance, mean^2 error
true_mu <- mu[1]
Ba_hat.avg <- mean(Ba_hat)
Ba_hat.bias <- Ba_hat.avg - true_mu
Ba_hat.pcbias <- (Ba_hat.bias / true_mu) * 100
Ba_hat.var <- var(Ba_hat)
Ba_hat.mean2 <- Ba_hat.bias^2 + Ba_hat.var

## Tabulated results
results.summary <- data.frame(mu=true_mu,
                              mean=Ba_hat.avg,
                              bias=Ba_hat.bias,
                              pc_bias=Ba_hat.pcbias,
                              var=Ba_hat.var,
                              mean2_err=Ba_hat.mean2)

rownames(results.summary) <- ""
results.summary

Ba_hat_hist_full <- data.frame(Ba_hat=Ba_hat)
ggplot(Ba_hat_hist_full, aes(x=Ba_hat)) +
  geom_histogram(bins = 20) +
  geom_vline(aes(xintercept=mean(Ba_hat)),
             color="red", linetype="dashed", size=1, alpha=.5) +
  ggtitle("Histogram of Ba_hat (all values)")

Ba_hat_hist <- data.frame(Ba_hat=Ba_hat[Ba_hat > mean(Ba_hat) - 3*sd(Ba_hat) & Ba_hat < mean(Ba_hat) + 3*sd(Ba_hat)])

## Plot histogram WITHOUT outliers
ggplot(Ba_hat_hist, aes(x=Ba_hat)) +
  geom_histogram(bins = 20) +
  geom_vline(aes(xintercept=mean(Ba_hat)),
             color="red", linetype="dashed", size=1, alpha=.5) +
  ggtitle("Histogram of Ba_hat (no outliers)")
```

```{r seed -23018794}
rownames(B_closed) <- c("Beta_0","Beta_a")
colnames(B_closed) <- c("")
B_closed
summary(1 / sim.data$E.Wx)
tanh_title <- expression("Histogram of "*1/tanh(hat(alpha)^T*x)*" at seed -23018794")
hist(1 / sim.data$E.Wx,main=tanh_title, xlab=expression(1/tanh(hat(alpha)^T*x)),breaks = 20, col = "red")
hist(sim.data$R,main="Histogram of R = Y/tanh, seed -23018794",xlab="R", col="red")
hist(sim.data$R[sim.data$R > 1000],main="Histogram of R > 1000, seed -23018794",xlab="R", col="red")
```

```{r seed -23019286}
load("tanh_Ba1670_data.RData")
rownames(B_closed) <- c("Beta_0","Beta_a")
colnames(B_closed) <- c("")
B_closed
summary(1 / sim.data$E.Wx)
tanh_title <- expression("Histogram of "*1/tanh(hat(alpha)^T*x)*" at seed -23019286")
hist(1 / sim.data$E.Wx,main=tanh_title, xlab=expression(1/tanh(hat(alpha)^T*x)),breaks = 20, col = "red")
hist(sim.data$R,main="Histogram of R = Y/tanh, seed -23019286",xlab="R", col="red")
hist(sim.data$R[sim.data$R > 1000],main="Histogram of R > 1000, seed -23019286",xlab="R", col="red")
```

```{r seed -23018687}
load("C:/Users/Jimmy/Desktop/git/Summer-2016/R/Newton-Raphson/NLS_NR/Markdown Output/tanh_Ba1_68_data.RData")
rownames(B_closed) <- c("Beta_0","Beta_a")
colnames(B_closed) <- c("")
B_closed
summary(1 / sim.data$E.Wx)
tanh_title <- expression("Histogram of "*1/tanh(hat(alpha)^T*x)*" at seed -23018687")
hist(1 / sim.data$E.Wx,main=tanh_title, xlab=expression(1/tanh(hat(alpha)^T*x)),breaks = 20, col = "red")
hist(sim.data$R,main="Histogram of R = Y/tanh, seed -23018687",xlab="R", col="red")
```

```{r seed -23018899}
load("C:/Users/Jimmy/Desktop/git/Summer-2016/R/Newton-Raphson/NLS_NR/Markdown Output/tanh_Ba1_57_data.RData")
rownames(B_closed) <- c("Beta_0","Beta_a")
colnames(B_closed) <- c("")
B_closed
summary(1 / sim.data$E.Wx)
tanh_title <- expression("Histogram of "*1/tanh(hat(alpha)^T*x)*" at seed -23018899")
hist(1 / sim.data$E.Wx,main=tanh_title, xlab=expression(1/tanh(hat(alpha)^T*x)),breaks = 20, col = "red")
hist(sim.data$R,main="Histogram of R = Y/tanh, seed -23018899",xlab="R", col="red")
```